// <auto-generated />
namespace Project124125125.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class testerdawawd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testerdawawd));
        
        string IMigrationMetadata.Id
        {
            get { return "201903100132231_testerdawawd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
